ej.base.L10n.load({
    'it-IT': {
        'PdfViewer': {
            "PdfViewer": "Visualizzatore PDF",
            "Cancel": "Annulla",
            "Download file": "Download file",
            "Download": "Scarica",
            "Enter Password": "Questo documento è protetto da password. Per favore inserire una password.",
            "File Corrupted": "File corrotto",
            "File Corrupted Content": "Il file è danneggiato e non può essere aperto.",
            "Fit Page": "Adatta alla pagina",
            "Fit Width": "Adatta larghezza",
            "Automatic": "Automatico",
            "Go To First Page": "Mostra la prima pagina",
            "Invalid Password": "Password errata. Per favore riprova.",
            "Next Page": "Mostra la pagina successiva",
            "OK": "ok",
            "Open": "Apri il file",
            "Page Number": "Numero di pagina corrente",
            "Previous Page": "Mostra la pagina precedente",
            "Go To Last Page": "Mostra l'ultima pagina",
            "Zoom": "Ingrandisci",
            "Zoom In": "Ingrandire",
            "Zoom Out": "Rimpicciolire",
            "Page Thumbnails": "Miniature di pagina",
            "Bookmarks": "Segnalibri",
            "Print": "Stampa file",
            "Password Protected": "Password richiesta",
            "Copy": "Copia",
            "Text Selection": "Strumento di selezione del testo",
            "Panning": "Panning",
            "Text Search": "Trova testo",
            "Find in document": "Trova nel documento",
            "Match case": "Caso di corrispondenza",
            "Apply": "Applicare",
            "GoToPage": "Vai alla pagina",
            "No matches": "Il visualizzatore ha terminato la ricerca del documento. Non sono state trovate altre corrispondenze",
            "No Text Found": "Nessun testo trovato",
            "Undo": "Annulla modifica",
            "Redo": "Ripeti modifica",
            "Annotation": "Aggiungi o modifica annotazioni",
            "Highlight": "Testo evidenziato",
            "Underline": "Sottolinea il testo",
            "Strikethrough": "Testo barrato",
            "Delete": "Elimina annotazione",
            "Opacity": "Opacità",
            "Color edit": "Cambia colore",
            "Opacity edit": "Cambia opacità",
            "Highlight context": "Evidenziare",
            "Underline context": "Sottolineare",
            "Strikethrough context": "Colpisci",
            "Server error": "Il servizio Web non è in ascolto. PDF Viewer dipende dal servizio web per tutte le sue funzionalità. Si prega di avviare il servizio Web per continuare.",
            "Open text": "Aperto",
            "First text": "Prima pagina",
            "Previous text": "Pagina precedente",
            "Next text": "Pagina successiva",
            "Last text": "Ultima pagina",
            "Zoom in text": "Ingrandire",
            "Zoom out text": "Zoom indietro",
            "Selection text": "Selezione",
            "Pan text": "Pan text",
            "Print text": "Stampa",
            "Search text": "Ricerca",
            "Annotation Edit text": "Modifica annotazione",
            "Line Thickness": "Spessore della linea",
            "Line Properties": "Proprietà linea",
            "Start Arrow": "Inizia la freccia",
            "End Arrow": "Freccia finale",
            "Line Style": "Stile di linea",
            "Fill Color": "Colore di riempimento",
            "Line Color": "Linea di colore",
            "None": "Nessuna",
            "Open Arrow": "Aperto",
            "Closed Arrow": "Chiuso",
            "Round Arrow": "Round",
            "Square Arrow": "Square",
            "Diamond Arrow": "Diamond",
            "Cut": "Tagliare",
            "Paste": "Incolla",
            "Delete Context": "Elimina",
            "Properties": "Proprietà",
            "Add Stamp": "Aggiungi timbro",
            "Add Shapes": "Aggiungi forme",
            "Stroke edit": "Cambia colore tratto",
            "Change thickness": "Cambia spessore del bordo",
            "Add line": "Aggiungi linea",
            "Add arrow": "Aggiungi freccia",
            "Add rectangle": "Aggiungi rettangolo",
            "Add circle": "Aggiungi cerchia",
            "Add polygon": "Aggiungi poligono",
            "Add Comments": "Aggiungi commenti",
            "Comments": "Commenti",
            "No Comments Yet": "Ancora nessun commento",
            "Accepted": "Accettato",
            "Completed": "Completato",
            "Cancelled": "Annullato",
            "Rejected": "Respinto",
            "Leader Length": "Lunghezza del leader",
            "Scale Ratio": "Rapporto di scala",
            "Calibrate": "Calibrare",
            "Calibrate Distance": "Calibra distanza",
            "Calibrate Perimeter": "Calibra perimetro",
            "Calibrate Area": "Calibra area",
            "Calibrate Radius": "Calibra raggio",
            "Calibrate Volume": "Calibra volume",
            "Export annotations": "Salva annotazioni"
        }
    }
});


const docsAzioniPdf = {
    Carica : 0,
    CaricaRiepilogo : 1,
    Salva : 2,
    UnisciPdf : 3,
    Ricarica : 4,
    CancellaPagina: 10,
    RuotaPagina90: 11,
    RuotaPagina270: 12,
    SpostaPagina: 13 
}
