CREATE VIEW [dbo].[vDocs]
AS
SELECT [stream_id]
      ,[file_stream]
      ,[name]
      ,CONVERT(VARCHAR(4000),[path_locator]) AS [path_locator]
      ,CONVERT(VARCHAR(4000),[parent_path_locator]) AS [parent_path_locator]
      ,[file_type]
      ,[cached_file_size]
      ,[creation_time]
      ,[last_write_time]
      ,[last_access_time]
      ,[is_directory]
      ,[is_offline]
      ,[is_hidden]
      ,[is_readonly]
      ,[is_archive]
      ,[is_system]
      ,[is_temporary]
  FROM [dbo].Docs
